export const threadPosts = [
  {
    title: "Exploring the Unknown",
    subtitle: "Unveiling mysteries beyond our imagination",
    img: "https://picsum.photos/seed/Exploring+the+Unknown/300",
    topic: "Science and Discovery",
    topics: true,
  },
  {
    title: "A Culinary Adventure",
    subtitle: "From kitchen experiments to gourmet delights",
    img: "https://picsum.photos/seed/A+Culinary+Adventure/300",
    topic: "Food and Cooking",
    topics: true,
  },
  {
    title: "Through the Lens",
    subtitle: "Capturing moments that last a lifetime",
    img: "https://picsum.photos/seed/Through+the+Lens/300",
    topic: "Photography",
    topics: true,
  },
  {
    title: "Beyond the Pages",
    subtitle: "Diving into the world of literature",
    img: "https://picsum.photos/seed/Beyond+the+Pages/300",
    topic: "Literature and Books",
    topics: true,
  },
  {
    title: "Mindful Living",
    subtitle: "Embracing the present moment",
    img: "https://picsum.photos/seed/Mindful+Living/300",
    topic: "Wellness and Mindfulness",
    topics: true,
  },
  {
    title: "Tech Talk",
    subtitle: "Navigating the digital landscape",
    img: "https://picsum.photos/seed/Tech+Talk/300",
    topic: "Technology Trends",
    topics: true,
  },
  {
    title: "Musical Harmony",
    subtitle: "Notes that resonate with the soul",
    img: "https://picsum.photos/seed/Musical+Harmony/300",
    topic: "Music and Harmony",
    topics: true,
  },
  {
    title: "Fitness Fusion",
    subtitle: "Blending workouts for a healthier you",
    img: "https://picsum.photos/seed/Fitness+Fusion/300",
    topic: "Health and Fitness",
    topics: true,
  },
  {
    title: "Green Thumb Chronicles",
    subtitle: "Cultivating a garden of possibilities",
    img: "https://picsum.photos/seed/Green+Thumb+Chronicles/300",
    topic: "Gardening and Nature",
    topics: true,
  },
  {
    title: "Cosmic Wonders",
    subtitle: "Journey through the vastness of space",
    img: "https://picsum.photos/seed/Cosmic+Wonders/300",
    topic: "Astronomy and Space",
    topics: true,
  },
];
